### ISSUE TITLE
Proxmox 5.3 script compatible?

### ISSUE THREAD

**Issue by dreamserver-ro** [ayufan/pve-patches#11]
Hi, 

Can you update the script to be compatible with the version 5.3 ?

@ayufan 

Thank you

**Comment by chiva** [comment]
I did a compare between 5.2-1 and 5.3 affected files in original condition and there are no changes that should affect, as the backup code section hasn't changed anything between versions.

Also applied the patches with the script in a 5.3 Proxmox fresh install and it worked as expected.

**Comment by dreamserver-ro** [comment]
Thank You !
I can confirm is working with version 5.3. 
Keep up this great work!

**Comment by FitzChevalerie-22** [comment]
Hello,
You work really well.
I also meet a little trouble but with the version
 `pve-manager/5.3-5/97ae681d  (running kernel: 4.15.18-8-pve)`
result is
```
root @ proxmox: ~ pvp-patches # bash pve-5.2-2-diff-backup-addon test
Proxmox VE 5.1 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

pve-5.2-2-diff-backup-addon: line 402: patch: command not found
pve-5.2-2-diff-backup-addon: line 402: patch: command not found
```

Thanks

**Comment by Power2All** [comment]
It's still buggy.
vzdump and pct dump import will error with the latest patch.

```
  Logical volume "vm-200-disk-0" successfully removed
Undefined subroutine &PVE::Storage::get_full_backup called at /usr/share/perl5/PVE/LXC/Create.pm line 114.
ERROR: Backup of VM 100 failed - command 'set -o pipefail && tar cpf - --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' --one-file-system '--warning=no-file-ignored' '--directory=/var/lib/vz/dump/vzdump-lxc-100-2018_12_28-09_34_02.tmp' ./etc/vzdump/pct.conf ./etc/vzdump/pct.fw '--directory=/mnt/vzsnap0' --no-anchored '--exclude=lost+found' --anchored '--exclude=./tmp/?*' '--exclude=./var/tmp/?*' '--exclude=./var/run/?*.pid' ./' failed: got signal 13
INFO: Backup job finished with errors
job errors
```

Please fix :)

**Comment by martiGIT** [comment]
> ```
> pve-5.2-2-diff-backup-addon: line 402: patch: command not found
> pve-5.2-2-diff-backup-addon: line 402: patch: command not found
> ```
you have to install patch
```
 apt-get install patch
```

**Comment by martiGIT** [comment]
> Also applied the patches with the script in a 5.3 Proxmox fresh install and it worked as expected.

I have a problem with 5.3-6 after clicking "full backup every X days" in web-gui i got an error
```
Parameter verification failed. (400)
fullbackup: property is not defined in schema and the schema does not allow additional properties
```

also tried to uninstall patches, reinstall pve-manager qemu-server libpve-storage-perl, without success

**Comment by ayufan** [comment]
Hm. Will test that :)

**Comment by chiva** [comment]
@martiGIT: any of the following can fix that issue (which is not related with being on 5.3)

1. Refresh browser
2. Run `service pveproxy restart` and `service pvedaemon restart`, but not from the shell inside the Proxmox panel, login from a ssh terminal.
3. Clear cache and refresh browser
4. Reboot server

**Comment by martiGIT** [comment]
> @martiGIT: any of the following can fix that issue (which is not related with being on 5.3)
> 
> 1. Refresh browser
> 2. Run `service pveproxy restart` and `service pvedaemon restart`, but not from the shell inside the Proxmox panel, login from a ssh terminal.
> 3. Clear cache and refresh browser
> 4. Reboot server

looks like I have to do point 1,2 and 3 above to make it works at 5.3-8. Thanks for support

**Comment by ayufan** [comment]
I updated patch for 5.3-9 and fixed a bunch of smaller bugs :)
