### ISSUE TITLE
Error on 3 nodes Ceph Proxmox 5.3-8 Cluster

### ISSUE THREAD

**Issue by aracno** [ayufan/pve-patches#13]
Hi,

iam getting this error:

Hunk #5 succeeded at 1016 (offset 1 line).
Hunk #6 succeeded at 1028 (offset 1 line).
Hunk #7 succeeded at 1039 (offset 1 line).
patching file VZDump/LXC.pm
patching file VZDump/QemuServer.pm
PATCHED: /usr/share/perl5/PVE/
Job for pveproxy.service failed because the control process exited with error code.
See systemctl status pveproxy.service and journalctl -xe for details.
Job for pvedaemon.service failed because the control process exited with error code.
See systemctl status pvedaemon.service and journalctl -xe for details.

Output off journalctl -xe:

-- Unit pveproxy.service has begun starting up.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Global symbol "$uncomp" requires explicit package name (did you forget to declare "my $uncomp"?) at /usr/share/perl5/PVE/QemuServer.pm line 5989, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/QemuConfig.pm line 8, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/QemuConfig.pm line 8, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/HA/Resources/PVEVM.pm line 10, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/HA/Resources/PVEVM.pm line 17, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/HA/Env/PVE2.pm line 20, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/HA/Env/PVE2.pm line 20, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/VZDump.pm line 18, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/VZDump.pm line 18, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/API2/Backup.pm line 15, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2/Backup.pm line 15, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/API2/Cluster.pm line 15, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2/Cluster.pm line 15, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/API2.pm line 13, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2.pm line 13, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/share/perl5/PVE/Service/pveproxy.pm line 15, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/Service/pveproxy.pm line 15, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: Compilation failed in require at /usr/bin/pveproxy line 11, <DATA> line 755.
Feb 12 19:05:11 pvenode01 pveproxy[9870]: BEGIN failed--compilation aborted at /usr/bin/pveproxy line 11, <DATA> line 755.
Feb 12 19:05:11 pvenode01 systemd[1]: pveproxy.service: Control process exited, code=exited status=255
Feb 12 19:05:11 pvenode01 systemd[1]: Failed to start PVE API Proxy Server.
-- Subject: Unit pveproxy.service has failed

Thanks for your help.

**Comment by ayufan** [comment]
Can you test latest patch for 5.3-9?

**Comment by theassyrian** [comment]
crap I got this error on my latest apt get upgrade, I will post my fix as soon as I figure it out

**Comment by theassyrian** [comment]
apt-get dist-upgrade fixed my issue thank you
