### ISSUE TITLE
Question for you Kamil..

### ISSUE THREAD

**Issue by abclution** [ayufan/pve-patches#15]
Big fan, your patches are a huge improvement to proxmox backup system and hugely appreciated.

My question is, for your own use, how many differential backups do you use before taking a new full backup, personally?

I understand the risk that each previous differential file is need to restore a machine up till the point one wishes to restore to, but if each diff backup (as well as the initial full) is backed up and securely stored (zfs) as well, is it feasible to do 1 full per year?  What do you personally do?

**Comment by ayufan** [comment]
Full backup every week, and as many differentials as needed.

To restore you need full backup and latest differential.
The situation that you describe is incremental backups.

Yes, it is feasible, but it is also very likely that your differential will grow over time,
as amount of data changed compared to full backup will be substantional.

**Comment by abclution** [comment]
Hi thanks for the reply.
I found out I am actually limited via the GUI to a maximum of 60 (Full Backup Every)

Yes you are right, essentially if the aggregate changes of all diff snapshots exceed a certain amount, a full backup is  a better choice.

I was trying to setup a daily full (but only stored changed data) with a combo of your patches and borg backup.  Many of my vms I don't move very much data in and out so the diff would be fairly predictably small. 

"As many differentials as needed"
Differential backups need to be called by the backup scheduler right? They cannot be run via the gui on as needed basis can they?

**Comment by ayufan** [comment]
Yes. Diffs are run on schedule

**Comment by abclution** [comment]
Thanks, appreciate your time.
