### ISSUE TITLE
Proxmox 5.4-1 Issue

### ISSUE THREAD

**Issue by christophenouvel** [ayufan/pve-patches#16]
Hi,

pveproxy will fail to start after applying latest patch.
pveproxy starts normally without applying patch.

Sample output with aptch applied :
systemctl status pveproxy
● pveproxy.service - PVE API Proxy Server
   Loaded: loaded (/lib/systemd/system/pveproxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-04-25 09:12:12 CEST; 13min ago
 Main PID: 19852 (code=exited, status=0/SUCCESS)
      CPU: 1.298s

Apr 25 09:12:12 pveproxy[8763]: Compilation failed in require at /usr/share/perl5/PVE/API2.pm line 13.
Apr 25 09:12:12 pveproxy[8763]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2.pm line 13.
Apr 25 09:12:12 pveproxy[8763]: Compilation failed in require at /usr/share/perl5/PVE/Service/pveproxy.pm line
Apr 25 09:12:12 pveproxy[8763]: BEGIN failed--compilation aborted at /usr/share/perl5/PVE/Service/pveproxy.pm
Apr 25 09:12:12 pveproxy[8763]: Compilation failed in require at /usr/bin/pveproxy line 11.
Apr 25 09:12:12 pveproxy[8763]: BEGIN failed--compilation aborted at /usr/bin/pveproxy line 11.
Apr 25 09:12:12 systemd[1]: pveproxy.service: Control process exited, code=exited status=255
Apr 25 09:12:12 systemd[1]: Failed to start PVE API Proxy Server.
Apr 25 09:12:12 systemd[1]: pveproxy.service: Unit entered failed state.
Apr 25 09:12:12 systemd[1]: pveproxy.service: Failed with result 'exit-code'.

Any idea?

  Thanks,

    Christophe.

**Comment by ayufan** [comment]
Find it here: https://github.com/ayufan/pve-patches/commit/b75e7dfb501862e848e5619412de01a0e8297556

**Comment by christophenouvel** [comment]
Seems to apply cleanly and work correctly right now,

Thank you,

  Christophe.
