### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by B4unty** [ayufan/pve-patches#18]
There is a problem with the installation. PVE is 5.4-3`bash pve-5.4-5-diff-backup-addon apply
Proxmox VE 5.4-5 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
checking file usr/share/perl5/PVE/LXC/Create.pm
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored
checking file usr/share/perl5/PVE/QemuServer.pm
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored
checking file usr/share/perl5/PVE/Storage.pm
Reversed (or previously applied) patch detected!  Skipping patch.
4 out of 4 hunks ignored
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
checking file usr/share/perl5/PVE/VZDump.pm
Reversed (or previously applied) patch detected!  Skipping patch.
7 out of 7 hunks ignored
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored
FAILED to apply!
`

**Comment by terdinatore** [comment]
I guess you will already have figured it out by now, but your install is/was messed up. As per the instructions you should reinstall the packages that are part of the patch:
```
apt-get --reinstall install pve-manager pve-container qemu-server libpve-storage-perl 
```
After this you should be able to `apply` the patches again like you would on a clean system.
