### ISSUE TITLE
Proxmox VE 6.0 Compatibility - Has anyone tried the patches yet on PVE 6? 

### ISSUE THREAD

**Issue by abclution** [ayufan/pve-patches#20]
Since I don't see any issues yet, my guess is it works fine, or no one brave enough to try it yet. Just wondering. :)

**Comment by WhiteNoseThunderPants** [comment]
@abclution I would imagine it does not work, have you tried it?

**Comment by ayufan** [comment]
I did apply that on 6.0 BETA and I did run `selftest-qemu/lxc` it seems to work fine :)

**Comment by WhiteNoseThunderPants** [comment]
Ok, awesome, I figured enough changed that it wouldn't work. I will give it a try myself.

**Comment by ayufan** [comment]
I see that it is no longer applying on `6.0-5`, it was working on `6.0-1` :)

**Comment by ayufan** [comment]
OK. The support to `6.0-1` and `6.0-5` is pushed: https://github.com/ayufan/pve-patches/blob/master/pve-6.0-5-diff-backup-addon.
