### ISSUE TITLE
patch for version 6.0.6

### ISSUE THREAD

**Issue by abhishekakt1** [ayufan/pve-patches#22]
Hello

I migrated proxmox to new server. After update, I noticed new version 6.0.6. However, I couldn't find patch for 6.0.6. Not sure if I can use 6.0.5 on 6.0.6. Please suggest

Thanks

Abhishek

**Comment by ayufan** [comment]
The 6.0.5 patch should apply cleanly.

**Comment by jhusarek** [comment]
Hi,
I am using this combination and it is really cleanly.

Many thanks to ayufan! ;-)

**Comment by milindsalwe** [comment]
Patch applies but error while using

Please resolve the issue. Can not use the patch.

<img width="600" alt="Screenshot 2019-08-26 at 12 56 25 AM" src="https://user-images.githubusercontent.com/25187021/63654784-a3e48980-c79c-11e9-8446-278c4c531ab6.png">
<img width="608" alt="Screenshot 2019-08-26 at 12 55 52 AM" src="https://user-images.githubusercontent.com/25187021/63654787-af37b500-c79c-11e9-859f-9e533c63fbec.png">

**Comment by milindsalwe** [comment]
Should I open a fresh issue ?

**Comment by milindsalwe** [comment]
Sorry I forgot to mention that I am on 6.0.6
