### ISSUE TITLE
Not working with latest Proxmox 6.07

### ISSUE THREAD

**Issue by dkmn-123** [ayufan/pve-patches#25]
oot@prox:/mnt/b/prox-install/pve-patches/pve-patches# bash pve-6.0-5-diff-backup-addon apply
Proxmox VE 6.0-5 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 37953 (offset 8068 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #1 succeeded at 71 (offset -1 lines).
Hunk #2 succeeded at 109 (offset -1 lines).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5960 (offset 618 lines).
Hunk #2 succeeded at 6323 (offset 635 lines).
Hunk #3 succeeded at 6649 (offset 659 lines).
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 succeeded at 512 (offset 18 lines).
Hunk #2 succeeded at 1263 (offset -71 lines).
Hunk #3 succeeded at 1309 (offset -71 lines).
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Hunk #1 succeeded at 423 (offset 25 lines).
Hunk #2 FAILED at 925.
1 out of 2 hunks FAILED
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 succeeded at 170 (offset -2 lines).
Hunk #4 succeeded at 812 (offset 9 lines).
Hunk #5 succeeded at 1018 (offset 2 lines).
Hunk #6 succeeded at 1030 (offset 2 lines).
Hunk #7 succeeded at 1041 (offset 2 lines).
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 302 (offset 6 lines).
Hunk #2 succeeded at 362 (offset 6 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
FAILED to apply!
root@prox:/mnt/b/prox-install/pve-patches/pve-patches# uname
Linux
root@prox:/mnt/b/prox-install/pve-patches/pve-patches# uname -r
5.0.21-2-pve

**Comment by Midas1989** [comment]
Yes i have the same problem.
I hope a release is coming

**Comment by magno-santos** [comment]
Same here.

**Comment by nikolauspolak** [comment]
Sorry that I'm unable to send a pull request or similar, but the fix is easy - move the following 3 lines up in the script - diff file:
```
351a352
>             next if defined($vmid) && $fn !~  m/\S+-$vmid-\S+/;
354d354
<             next if defined($vmid) && $fn !~  m/\S+-$vmid-\S+/;
```
so it reads
```
        } elsif ($tt eq 'backup') {
            next if defined($vmid) && $fn !~  m/\S+-$vmid-\S+/;
-           next if $fn !~ m!/([^/]+\.(tar|tar\.gz|tar\.lzo|tgz|vma|vma\.gz|vma\.lzo))$!;
+           next if $fn !~ m!/([^/]+\.(tar|tar\.gz|tar\.lzo|tgz|vma|vma\.gz|vma\.lzo|vcdi....
```

**Comment by dkmn-123** [comment]
Thank you for the help.
I tried your solution at the latest upgrade  (including qemu released today) and it failed:

Proxmox VE 6.0-5 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 37953 (offset 8068 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #1 succeeded at 71 (offset -1 lines).
Hunk #2 succeeded at 109 (offset -1 lines).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 6029 (offset 687 lines).
Hunk #2 succeeded at 6392 (offset 704 lines).
Hunk #3 succeeded at 6718 (offset 728 lines).
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 succeeded at 512 (offset 18 lines).
Hunk #2 succeeded at 1263 (offset -71 lines).
Hunk #3 succeeded at 1309 (offset -71 lines).
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Hunk #1 succeeded at 423 (offset 25 lines).
Hunk #2 FAILED at 925.
1 out of 2 hunks FAILED
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 succeeded at 170 (offset -2 lines).
Hunk #4 succeeded at 812 (offset 9 lines).
Hunk #5 succeeded at 1018 (offset 2 lines).
Hunk #6 succeeded at 1030 (offset 2 lines).
Hunk #7 succeeded at 1041 (offset 2 lines).
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 302 (offset 6 lines).
Hunk #2 succeeded at 362 (offset 6 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
FAILED to apply!

**Comment by marcin-github** [comment]
I had to add `-F 20` to diff parameters to patch proxmox.

**Comment by dkmn-123** [comment]
Where did you add -F 20?

**Comment by ayufan** [comment]
I will update patch by end of week

**Comment by marcin-github** [comment]
@pdionisis 
quick workarround is:
```
--- a/pve-6.0-5-diff-backup-addon
+++ b/pve-6.0-5-diff-backup-addon
@@ -74,9 +74,9 @@ revert)
   ;;

 apply)
-  if patch_apply / --dry-run
+  if patch_apply / --dry-run -F 20
   then
-    print_and_run patch_apply /
+    print_and_run patch_apply / -F 20
     echo "APPLIED"
   else
     echo "FAILED to apply!"
@@ -89,7 +89,7 @@ apply)
   ;;

 test)
-  print_and_run patch_apply / --dry-run --batch
+  print_and_run patch_apply / --dry-run --batch -F 20
   ;;

 patch)
```

**Comment by dkmn-123** [comment]
The patch succeeds but when I try to define a nerw backup with parameter full backup after XX days
I receive :
Parameter verification failed. (400)

fullbackup: property is not defined in schema and the schema does not allow additional properties

**Comment by ayufan** [comment]
I added a patch to 6.0-7.

As usual: apply, and force refresh browser when using.
