### ISSUE TITLE
apt install --reinstall "cannot be downloaded

### ISSUE THREAD

**Issue by My1** [ayufan/pve-patches#28]
Hello, I have a freshly installed proxmox 6.0-7 running and wanted to install the plugin, and well it failed, so below is that the "fairly straight-forward solution" of reinstalling doesnt seem to work because `Reinstallation of qemu-server is not possible, it cannot be downloaded.` internet is working though, as the git clone works nicely.

**Comment by ayufan** [comment]
This is removed and replaced with `reinstall` command.

**Comment by My1** [comment]
update readme maybe?
