### ISSUE TITLE
pve-patches 6.0-7 aren't compatible with proxmox 6.0-10

### ISSUE THREAD

**Issue by marcin-github** [ayufan/pve-patches#30]
```
# pveversion
pve-manager/6.0-10/337e50bb (running kernel: 5.2.0-73630-g66925f93919a)
```

```
# ./pve-6.0-7-diff-backup-addon apply
Proxmox VE 6.0-7 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 38316 (offset 137 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5972 (offset -57 lines).
Hunk #2 succeeded at 6335 (offset -57 lines).
Hunk #3 succeeded at 6661 (offset -57 lines).
checking file usr/share/perl5/PVE/Storage.pm
checking file usr/share/perl5/PVE/Storage/Plugin.pm
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 FAILED at 170.
Hunk #3 succeeded at 585 (offset -153 lines).
Hunk #4 succeeded at 652 (offset -153 lines).
Hunk #5 succeeded at 858 (offset -153 lines).
Hunk #6 succeeded at 870 (offset -153 lines).
Hunk #7 succeeded at 881 (offset -153 lines).
1 out of 7 hunks FAILED
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 303 (offset 1 line).
Hunk #2 succeeded at 363 (offset 1 line).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 235 (offset -2 lines).
Hunk #2 succeeded at 345 (offset -2 lines).
FAILED to apply!
```

**Comment by Power2All** [comment]
Check the pull request.
I've modified it for Proxmox -9 and -10 it might work too, not sure.

**Comment by dkmn-123** [comment]
Same problem here.
I have not installed the pull request (I do not know how yet)

Maybe an "official" compatibility update?

**Comment by tiagowippel** [comment]
> Check the pull request.
> I've modified it for Proxmox -9 and -10 it might work too, not sure.

Just test this pull request and it is NOT WORKING on Proxmox 6.0-11

Here is the output:

root@pve:~/pve-patches# bash pve-6.0-9-diff-backup-addon apply
Proxmox VE 6.0-9 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu
Updated by Power2All <info@power2all.com>

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 38372 (offset 71 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5944 (offset -85 lines).
Hunk #2 succeeded at 6307 (offset -85 lines).
Hunk #3 succeeded at 6633 with fuzz 1 (offset -85 lines).
checking file usr/share/perl5/PVE/Storage.pm
checking file usr/share/perl5/PVE/Storage/Plugin.pm
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 FAILED at 170.
Hunk #3 succeeded at 586 (offset -153 lines).
Hunk #4 succeeded at 651 (offset -153 lines).
Hunk #5 succeeded at 851 (offset -153 lines).
Hunk #6 succeeded at 869 (offset -153 lines).
Hunk #7 succeeded at 880 (offset -153 lines).
1 out of 7 hunks FAILED
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 303 (offset 1 line).
Hunk #2 succeeded at 363 (offset 1 line).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 243 (offset 6 lines).
Hunk #2 succeeded at 353 (offset 6 lines).
FAILED to apply!

**Comment by Power2All** [comment]
I need to upgrade my Proxmox this weekend anyway.
I'll fix the patch again then, it's not too hard to make ;)
Will update when I pushed it.

**Comment by ayufan** [comment]
I updated the patch and tested it against `6.0-11`. Small changes. I would advise to run it against this version.

**Comment by ayufan** [comment]
I also added a handy comment `reinstall`, that technically, if you are about to update you could run as a failsafe for cases when partial upgrade of system did happen (as not all components were udpated) and you did not revert the patch.

**Comment by Power2All** [comment]
Nice, thanks @ayufan
