### ISSUE TITLE
Can't backup CTs

### ISSUE THREAD

**Issue by Stan-Tastic** [ayufan/pve-patches#32]
I'm quite new to Proxmox, so perhaps this is not an issue with your delta backup patches - but this is not something I expected, either, so I'm looking for help where I can :-)

This is the output of an attempt at CT backup:

INFO: doing full backup, because no backup found in last 7 day(s)
INFO: Starting Backup of VM 153 (lxc)
INFO: Backup started at 2019-11-05 21:48:53
INFO: status = running
INFO: CT Name: sql-insert
INFO: backup mode: snapshot
INFO: ionice priority: 7
INFO: create storage snapshot 'vzdump'
INFO: creating archive '/mnt/pve/synology-nfs/dump/vzdump-lxc-153-2019_11_05-21_48_53.tar.gz'
INFO: tar: /mnt/pve/synology-nfs/dump/vzdump-lxc-153-2019_11_05-21_48_53.tmp: Cannot open: Permission denied
INFO: tar: Error is not recoverable: exiting now
INFO: remove vzdump snapshot
ERROR: Backup of VM 153 failed - command 'set -o pipefail && lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar cpf - --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' --one-file-system '--warning=no-file-ignored' '--directory=/mnt/pve/synology-nfs/dump/vzdump-lxc-153-2019_11_05-21_48_53.tmp' ./etc/vzdump/pct.conf ./etc/vzdump/pct.fw '--directory=/mnt/vzsnap0' --no-anchored '--exclude=lost+found' --anchored '--exclude=./tmp/?*' '--exclude=./var/tmp/?*' '--exclude=./var/run/?*.pid' ./ | gzip --rsyncable >/mnt/pve/synology-nfs/dump/vzdump-lxc-153-2019_11_05-21_48_53.tar.dat' failed: exit code 2
INFO: Failed at 2019-11-05 21:48:53

I'm not sure why tar doesn't have permission to create archive for container... VM backups were successful. Is there something I could do to fix this?

**Comment by ayufan** [comment]
This seems to be misconfiguration of NAS and NFS.

**Comment by Stan-Tastic** [comment]
That would be my first guess, but VM snapshots go through without any issue:

INFO: creating archive '/mnt/pve/synology-nfs/dump/vzdump-qemu-300-2019_11_13-23_38_42.vma.gz--differential-2019_11_14-23_45_27.vcdiff'
INFO: started backup task 'fa61cae9-c7b1-4b79-95e4-834e23b861c4'
INFO: status: 0% (520814592/137438953472), sparse 0% (182718464), duration 3, read/write 173/112 MB/s

(and so on, until backup is taken).

So what's the difference between doing CT and VM backups?
