### ISSUE TITLE
Patch not workink on Proxmox 6.0-11

### ISSUE THREAD

**Issue by tiagowippel** [ayufan/pve-patches#33]
root@pve:~/pve-patches# bash pve-6.0-7-diff-backup-addon apply
Proxmox VE 6.0-7 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 38372 (offset 193 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5944 (offset -85 lines).
Hunk #2 succeeded at 6307 (offset -85 lines).
Hunk #3 succeeded at 6633 (offset -85 lines).
checking file usr/share/perl5/PVE/Storage.pm
checking file usr/share/perl5/PVE/Storage/Plugin.pm
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 FAILED at 170.
Hunk #3 succeeded at 585 (offset -153 lines).
Hunk #4 succeeded at 652 (offset -153 lines).
Hunk #5 succeeded at 858 (offset -153 lines).
Hunk #6 succeeded at 870 (offset -153 lines).
Hunk #7 succeeded at 881 (offset -153 lines).
1 out of 7 hunks FAILED
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 303 (offset 1 line).
Hunk #2 succeeded at 363 (offset 1 line).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 243 (offset 6 lines).
Hunk #2 succeeded at 353 (offset 6 lines).
FAILED to apply!

**Comment by ayufan** [comment]
This is fixed as of latest commit.
