### ISSUE TITLE
pve-xdelta3 package version

### ISSUE THREAD

**Issue by KlugFR** [ayufan/pve-patches#34]
Hello.

The install doc states we should "latest version of pve-xdelta3" using this command: 
dpkg -i pve-xdelta3_3.0.6-1_amd64.deb

The same documentation links to this repo: https://github.com/ayufan/pve-xdelta3    
This repo is xdelta3 3.0.11, with lzma support included.

There's quite a difference between the repo (3.0.11) and the deb package (3.0.6, august 2013).

Shouldn't the patch install download the last package?
It's here: https://github.com/ayufan/pve-xdelta3/releases/download/v3.0.11/pve-xdelta3_3.0.11-dfsg-1ubuntu1ayufan1_amd64.deb

And shouldn't the documentation ask to install this package (3.0.11)?

**Comment by KlugFR** [comment]
It seems this 3.0.11 version supports the lzma compression that can be multithreaded.

**Comment by dkmn-123** [comment]
I think all of us would love the extra speed.
But how about compression ratio of lzma?

Did anyone actually installed it to see if it works ok?

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
