### ISSUE TITLE
Full Backup Every entry not shown in WB Gui

### ISSUE THREAD

**Issue by Performance20** [ayufan/pve-patches#36]
Install like description without any errors but the new entry is not shown in the WEB Gui if I add a new backup task.

Proxmox 6.1-3 with the last patch pve-6.1-3-diff-backup-addon and pve-xdelta3_3.0.6-1_amd64.deb.

Any ideas 

Helge

**Comment by DanielCambray** [comment]
Same thing here with Proxmox 5.4-13. Path is applied correctly but nothing in the web gui.

**Comment by DanielCambray** [comment]
Ok. The solution was in another thread. I just have to force a refresh of the web browser...

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
