### ISSUE TITLE
Not anable add fullbackup parameter

### ISSUE THREAD

**Issue by alexinc2000** [ayufan/pve-patches#38]
Hi!
Proxmox V6.1-3 in cluster mode.
apply patch, install xdelta3 on any host.
when add parametr maxfiles - 3 and any parametr full backup every:
I take mistake:
Parameter verification failed. (400)
fullbackup: property is not defined in schema and the schema does not allow additional properties.
Any idea?
PS. I update to 6.1-5. Wil it work on this version?

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
