### ISSUE TITLE
Backup is fine, can't restore

### ISSUE THREAD

**Issue by ozzgit** [ayufan/pve-patches#39]
Hi,
I've tested it on version 6.05 and now on 6.1.5.
Backups are completely fine.
Restores only work on full backups.
Restores from differentials are throwing this error within 3 seconds:
TASK ERROR: command 'set -o pipefail && pve-xdelta3 -q -d -c -R -s /mnt/pve/BackupNFS/dump/vzdump-qemu-100-2020_01_27-17_27_39.vma.lzo /mnt/pve/BackupNFS/dump/vzdump-qemu-100-2020_01_27-17_27_39.vma.lzo--differential-2020_01_27-17_38_02.vcdiff | vma extract -v -r /var/tmp/vzdumptmp17813.fifo - /var/tmp/vzdumptmp17813' failed: got timeout

The restore was tested from NFS and from local disk. The destinations that were tested: NFS, local disks.
Previous version was 6.0.5 with 6.0.5 patch.
Right now there's 6.1.5 with 6.1.3 patch which was applied without problems.

The error is always the same.
Please assist.

Thank you!

**Comment by ayufan** [comment]
Interesting. I'm testing the script against local disk and so far it was fine. The potential problem can be that it might take long time to execute, as I test on small projects.

**Comment by ozzgit** [comment]
I tested it on a small vm.
Full backup = 700MB

**Comment by ozzgit** [comment]
Kamil, I saw you fixed a similar issue in #7  patch 5.3.9
what was it?

**Comment by ozzgit** [comment]
Analyzing the logs, the only thing that's relevant is that each time this comes up before it throws the timeout error:
traps: vma[9621] trap int3 ip:7fc1774ddc75 sp:7ffd12a3da10 error:0 in libglib-2.0.so.0.5800.3[7fc1774a5000+7e000]
Could it be a problem with xdelta? I'm using this version:
pve-xdelta3_3.0.11-dfsg-1ubuntu1ayufan1_amd64.deb
I also added this one now:
pve-xdelta3-dbgsym_3.0.11-dfsg-1ubuntu1ayufan1_amd64.ddeb

but it made no difference.
Earlier I also tried to go back to pve-xdelta3_3.0.6-1_amd64.deb.

What could it be? Am I the only one on version 6 here?

**Comment by ozzgit** [comment]
ok, so after another round of trying - it finally works.
The problem was the xdelta-3.0.11
Previously I tried the 3.0.6 version but I only tried to restore the files that were backed up via 3.0.11
which was the wrong way of testing.
Now I installed the 3.0.6 version, created full backup + differential and then tried to restore - works like a charm!
Thanks a lot for a great soft!!!

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
