### ISSUE TITLE
Virtual Environment 4.4-22/2728f613 - No file to patch.  Skipping patch. 

### ISSUE THREAD

**Issue by ghost** [ayufan/pve-patches#4]
root@pve03:~/pve-patches# bash pve-4.4-diff-backup-addon apply
Proxmox VE 4.4 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/ext6/pvemanagerlib.js b/ext6/pvemanagerlib.js
|index 7a92574..d2bca5b 100644
|--- a/ext6/pvemanagerlib.js
|+++ b/ext6/pvemanagerlib.js
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

**Comment by ayufan** [comment]
This is resolved.
