### ISSUE TITLE
Installed On PVE But Not Showing "Full Backup Every"

### ISSUE THREAD

**Issue by swartjie** [ayufan/pve-patches#40]
Hey Guys,

Can you please assist?
I installed the software following the guide on one of our cluster servers, but there is no "Full Backup Every" option available.

Do I need to install it on all servers for it to show? Or am I missing something?

Kind Regards

**Comment by akaoma** [comment]
Hey!
Just check your current release, the latest provided by ayufan is for 6.1-3 release.   
If yours is 6.1-4 or above, it should not work.   (today current release is 6.1-6)
Ayufan is making an excellent work (really! thanks by the way!), but it's definitely time-consuming to create/test each pack release so only some of them are released.
Also before upgrading your proxmox PVE check what if the latest pve-patches is available. (if not, don't upgrade your PVE)
Kind regards.

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
