### ISSUE TITLE
6.1-8 patch fails to apply

### ISSUE THREAD

**Issue by joshuazick1** [ayufan/pve-patches#41]
I was setting up a new Proxmox server today and was trying to apply your patch to it
It failed with this
```
root@pve0:~/pve-patches# bash pve-6.0-11-diff-backup-addon apply
Proxmox VE 6.0-7 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 38532 (offset 160 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #1 succeeded at 116 (offset 45 lines).
Hunk #2 succeeded at 154 (offset 45 lines).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5409 (offset -535 lines).
Hunk #2 succeeded at 5731 (offset -576 lines).
Hunk #3 succeeded at 6059 (offset -574 lines).
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 succeeded at 519 (offset 7 lines).
Hunk #2 succeeded at 1279 (offset 16 lines).
Hunk #3 succeeded at 1325 (offset 16 lines).
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Hunk #1 succeeded at 432 (offset 9 lines).
Hunk #2 succeeded at 919 (offset 6 lines).
checking file usr/share/perl5/PVE/VZDump/Common.pm
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #1 FAILED at 8.
Hunk #2 succeeded at 627 (offset 43 lines).
Hunk #3 FAILED at 651.
Hunk #4 FAILED at 830.
Hunk #5 FAILED at 842.
Hunk #6 succeeded at 944 with fuzz 1 (offset 91 lines).
4 out of 6 hunks FAILED
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 314 (offset 11 lines).
Hunk #2 succeeded at 409 (offset 46 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 249 (offset 6 lines).
Hunk #2 succeeded at 359 (offset 6 lines).
FAILED to apply!
```

**Comment by ivdok** [comment]
@joshuazick1 Temporary fix is to downgrade pve-manager to [version 6.1-7](http://download.proxmox.com/debian/dists/buster/pve-no-subscription/binary-amd64/pve-manager_6.1-7_amd64.deb):

```
pve-patches/pve-6.1-3-diff-backup-addon reinstall
dpkg -i pve-manager_6.1-7_amd64.deb
pve-patches/pve-6.1-3-diff-backup-addon apply
```

@ayufan Hunk #3 at @@ -635,13 +803,40 @@ is not directly compatible VZDump.pm, unfortunately - I couldn't wrap my head about how to adapt the patch, new version of subroutine looks entirely different.

**Comment by tillo** [comment]
> @joshuazick1 Temporary fix is to downgrade pve-manager to [version 6.1-7](http://download.proxmox.com/debian/dists/buster/pve-no-subscription/binary-amd64/pve-manager_6.1-7_amd64.deb):

The following may be easier to run for those who aren't familiar with wget or curl to download the previous pve-manager package:

```
pve-patches/pve-6.1-3-diff-backup-addon reinstall
apt -V install 'pve-manager=6.1-7*'
apt-mark hold pve-manager
pve-patches/pve-6.1-3-diff-backup-addon apply
```

This will make pve-manager stick to the 6.1-7 version and apt won't try to upgrade it anymore until you run:

```
apt-mark unhold pve-manager
```

Thank you @ayufan for all your work, it's really appreciated.
If you need any help following up with the upstream changes, please let me know.

**Comment by ivdok** [comment]
> apt-mark hold pve-manager

Bad idea, it's quite easy to forget about held packages, plus right now downgrading manager back one version works, since almost nothing else changed, but what it further changes in underlying components break that compatibility? Best course of action right now is to downgrade, sub to issue, and lay off apt update/upgrade for a bit.

**Comment by ayufan** [comment]
@ivdok @tillo @joshuazick1 

I updated patch to `6.1-8`.

I see that the Proxmox started working on Proxmox Backup Solution/Service (?). So, it might seem that relevance of this patch goes away in some time in the future. Lets see how much things they do change to make maintaining of this patch burden.
