### ISSUE TITLE
No changes in GUI pve 6.1-3

### ISSUE THREAD

**Issue by rafalefighter** [ayufan/pve-patches#42]
I applied this today on one of my pve 6.1-3 node from 4 node cluster. I cannot see any changes on web gui. neither  in backup pane in individual VM. I tried clear browser cache and incognito mode also

`root@pve:/tmp/pve-patches-master# bash pve-6.0-11-diff-backup-addon apply
Proxmox VE 6.0-7 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 38698 (offset 326 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #1 succeeded at 72 (offset 1 line).
Hunk #2 succeeded at 110 (offset 1 line).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5862 (offset -82 lines).
Hunk #2 succeeded at 6225 (offset -82 lines).
Hunk #3 succeeded at 6553 (offset -80 lines).
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 succeeded at 514 (offset 2 lines).
Hunk #2 succeeded at 1265 (offset 2 lines).
Hunk #3 succeeded at 1311 (offset 2 lines).
checking file usr/share/perl5/PVE/Storage/Plugin.pm
checking file usr/share/perl5/PVE/VZDump/Common.pm
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 succeeded at 613 (offset 28 lines).
Hunk #3 succeeded at 680 (offset 28 lines).
Hunk #4 succeeded at 886 (offset 28 lines).
Hunk #5 succeeded at 898 (offset 28 lines).
Hunk #6 succeeded at 909 (offset 28 lines).
checking file usr/share/perl5/PVE/VZDump/LXC.pm
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 246 (offset 3 lines).
Hunk #2 succeeded at 356 (offset 3 lines).
$ patch_apply /
patching file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 38698 (offset 326 lines).
patching file usr/share/perl5/PVE/LXC/Create.pm
Hunk #1 succeeded at 72 (offset 1 line).
Hunk #2 succeeded at 110 (offset 1 line).
patching file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5862 (offset -82 lines).
Hunk #2 succeeded at 6225 (offset -82 lines).
Hunk #3 succeeded at 6553 (offset -80 lines).
patching file usr/share/perl5/PVE/Storage.pm
Hunk #1 succeeded at 514 (offset 2 lines).
Hunk #2 succeeded at 1265 (offset 2 lines).
Hunk #3 succeeded at 1311 (offset 2 lines).
patching file usr/share/perl5/PVE/Storage/Plugin.pm
patching file usr/share/perl5/PVE/VZDump/Common.pm
patching file usr/share/perl5/PVE/VZDump.pm
Hunk #2 succeeded at 613 (offset 28 lines).
Hunk #3 succeeded at 680 (offset 28 lines).
Hunk #4 succeeded at 886 (offset 28 lines).
Hunk #5 succeeded at 898 (offset 28 lines).
Hunk #6 succeeded at 909 (offset 28 lines).
patching file usr/share/perl5/PVE/VZDump/LXC.pm
patching file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 246 (offset 3 lines).
Hunk #2 succeeded at 356 (offset 3 lines).
APPLIED

$ service pveproxy restart
$ service pvedaemon restart`

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
