### ISSUE TITLE
Patch script for 6.1-8 does not work on 6.1-8

### ISSUE THREAD

**Issue by jlegen** [ayufan/pve-patches#43]
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 242 with fuzz 2 (offset -7 lines).
Hunk #2 FAILED at 359.
1 out of 2 hunks FAILED

* there's no sub "archive" anymore, instead there are 2 now, looks like some major changes are coming ("Proxmox Backup Server"?) 
* patching sub "archive_vma" seems to do the job... still needs some testing

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
