### ISSUE TITLE
Extreme long time issue?

### ISSUE THREAD

**Issue by killmasta93** [ayufan/pve-patches#46]
Hi,
Currently did the test before and after and really long without the patches 3 hours and with the patch 26 hours

![Screenshot_2020-04-16_17-05-28](https://user-images.githubusercontent.com/13953629/79506862-b1d56c00-8004-11ea-8bd8-786ef5ecee74.png)
![Screenshot_2020-04-16_17-05-01](https://user-images.githubusercontent.com/13953629/79506863-b3069900-8004-11ea-98d1-a1fa0cb1eee5.png)

**Comment by killmasta93** [comment]
bump anyone?

**Comment by ayufan** [comment]
It seems to be a problem with xdelta3.

Can you try to install the https://github.com/ayufan/pve-xdelta3/releases/download/3.0.11.zstd/pve-xdelta3_3.0.11-dfsg-1ubuntu1.zstd.ayufan2_amd64.deb?

**Comment by killmasta93** [comment]
Hi there still the same issue takes way longer these are the logs

This is without the pve patches

https://pastebin.com/FB70Gbde

This is with the pvepatches i have to cancel the backup because it was taking way to long

https://pastebin.com/UWwx588t
