### ISSUE TITLE
fullbackup property not defined

### ISSUE THREAD

**Issue by jolypas** [ayufan/pve-patches#47]
Hello

I applied for 6.1.3
I got the new menu but impossible to validate because an issue on "Full backup every ..."

![image](https://user-images.githubusercontent.com/14258266/80277061-c09add80-86ec-11ea-9f3d-e900116c0532.png)

![image](https://user-images.githubusercontent.com/14258266/80277097-0657a600-86ed-11ea-9fc4-cb0af2c5d671.png)

any idea

Regards

**Comment by jolypas** [comment]
Update

after a reboot of the server I can configure but I face a another problem :

Full backups are working fine (if I put 0 in "Full backup every ....")
Differential backups are failing with "broken pipe" ...
Is there something different for differential backups to configure on the NFS storage (ports , ...) ?

logs 
100: 2020-04-26 11:18:22 INFO: Starting Backup of VM 100 (qemu)
100: 2020-04-26 11:18:22 INFO: status = running
100: 2020-04-26 11:18:24 INFO: update VM 100: -lock backup
100: 2020-04-26 11:18:24 INFO: VM Name: devhunt
100: 2020-04-26 11:18:24 INFO: include disk 'scsi0' 'local-lvm:vm-100-disk-0' 500G
100: 2020-04-26 11:18:24 INFO: backup mode: snapshot
100: 2020-04-26 11:18:24 INFO: ionice priority: 7
100: 2020-04-26 11:18:24 INFO: creating archive '/mnt/pve/vm7-nakivo/dump/vzdump-qemu-100-2020_04_26-09_44_41.vma.lzo--differential-2020_04_26-11_18_21.vcdiff'
100: 2020-04-26 11:18:24 INFO: started backup task '7df47b8a-de7f-4c6b-94e4-26fea00d41f3'
100: 2020-04-26 11:18:25 INFO: status: 0% (3801088/536870912000), sparse 0% (1249280), duration 1, read/write 3/2 MB/s
100: 2020-04-26 11:18:25 ERROR: vma_queue_write: write error - Broken pipe
100: 2020-04-26 11:18:25 INFO: aborting backup job
100: 2020-04-26 11:18:27 ERROR: Backup of VM 100 failed - vma_queue_write: write error - Broken pipe

Regards

**Comment by ayufan** [comment]
Please use 6.2-4: #50 (comment)
