### ISSUE TITLE
Full backup every X don't work

### ISSUE THREAD

**Issue by vdeville** [ayufan/pve-patches#48]
Hello
Thanks for your tool, i install on proxmox 6.1.8, no problem to patch.
The first backup is process as full, this is fine. But the parameter --fullbackup is not applied.

My command :
`vzdump 103 --mode snapshot --compress lzo --storage local --fullbackup 4`

After multiple exec of the command, only the first full backup is present all others is diff.

Files:
```
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_33_12.vcdiff
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_36_29.vcdiff
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_43_25.dat
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_48_08.vcdiff
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_50_22.vcdiff
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_51_59.vcdiff
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_54_16.vcdiff
/var/lib/vz/dump/vzdump-qemu-103-2020_04_29-09_26_56.vma.gz--differential-2020_04_29-09_56_57.vcdiff
```

Do you have an idea of what is wrong ?

Thanks

**Comment by ayufan** [comment]
This works fine. The `fullbackup` indicates how many full backups can be persisted. The differentials are controlled by amount of days of keeping them before a new full backup is created.

**Comment by vdeville** [comment]
Hello
I will retry in the next days, in the past this comportement doesn't work.
Thanks

**Comment by vdeville** [comment]
Hello @ayufan 
Just tested today with theses settings and create more than the max backup set, and always make differential.
<img width="580" alt="Capture d’écran 2020-06-01 à 14 11 12" src="https://user-images.githubusercontent.com/6104498/83407796-c1bcda00-a411-11ea-9468-5edc1fc9d4a8.png">
<img width="293" alt="Capture d’écran 2020-06-01 à 14 11 37" src="https://user-images.githubusercontent.com/6104498/83407834-d0a38c80-a411-11ea-99cd-c4c2a3df1672.png">
<img width="599" alt="Capture d’écran 2020-06-01 à 14 11 51" src="https://user-images.githubusercontent.com/6104498/83407852-da2cf480-a411-11ea-9a34-8ab342dae91e.png">

Thanks

**Comment by vakartel** [comment]
Because it count not backup-instances but days
