### ISSUE TITLE
No access web GUI since apply patch 6.1-8 (to) 6.1-11

### ISSUE THREAD

**Issue by DECIGrade** [ayufan/pve-patches#49]
> Now I have version 6.1-11 of Proxmox, but script doesn't work with this newest version.

Hello,

I have a Proxmox version 6.1-8 and git clone the pve-patches, I put "bash pve-5.4-5-diff-backup-addon apply" and I have this return :

root@ns3080769:~/pve-patches# bash pve-5.4-5-diff-backup-addon apply
Proxmox VE 5.4-5 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 40632 (offset 10747 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #1 succeeded at 116 (offset 44 lines).
Hunk #2 succeeded at 155 (offset 45 lines).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5613 (offset 271 lines).
Hunk #2 FAILED at 5688.
Hunk #3 succeeded at 6458 (offset 474 lines).
1 out of 3 hunks FAILED
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 FAILED at 494.
Hunk #2 FAILED at 780.
Hunk #3 succeeded at 1404 with fuzz 1 (offset 70 lines).
Hunk #4 succeeded at 1450 (offset 70 lines).
2 out of 4 hunks FAILED
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Hunk #1 FAILED at 398.
1 out of 1 hunk FAILED
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #1 FAILED at 8.
Hunk #2 FAILED at 171.
Hunk #3 succeeded at 636 (offset -101 lines).
Hunk #4 FAILED at 795.
Hunk #5 FAILED at 981.
Hunk #6 FAILED at 993.
Hunk #7 succeeded at 953 with fuzz 2 (offset -51 lines).
5 out of 7 hunks FAILED
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 319 (offset 23 lines).
Hunk #2 succeeded at 414 (offset 58 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 243 with fuzz 2 (offset 6 lines).
Hunk #2 FAILED at 347.
1 out of 2 hunks FAILED
FAILED to apply!

My VMs work but, now I can't access to my web manager, and pve-proxy fail...

root@ns3080769:~/pve-patches# pveproxy start
unknown file 'priv/acme/plugins.cfg' at /usr/share/perl5/PVE/Cluster.pm line 474.
Compilation failed in require at /usr/share/perl5/PVE/API2/ACMEAccount.pm line 13.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2/ACMEAccount.pm line 13.
Compilation failed in require at /usr/share/perl5/PVE/API2/Cluster.pm line 23.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2/Cluster.pm line 23.
Compilation failed in require at /usr/share/perl5/PVE/API2.pm line 14.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2.pm line 14.
Compilation failed in require at /usr/share/perl5/PVE/Service/pveproxy.pm line 16.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/Service/pveproxy.pm line 16.
Compilation failed in require at /usr/bin/pveproxy line 11.
BEGIN failed--compilation aborted at /usr/bin/pveproxy line 11.

Please help.

Best regards,
DECIGrade

**Comment by DECIGrade** [comment]
Ok, I have reinstall my pve-manager with 

> wget http://download.proxmox.com/debian/dists/buster/pve-no-subscription/binary-amd64/pve-manager_6.1-8_amd64.deb
> dpkg -i pve-manager_6.1-8_amd64.deb
> apt -V install 'pve-manager=6.1-8*'

And now seems fine, I can access to web manager with 6.1-8 version.

But, when I test the 6.1-8 script with test, I have always fail.

> root@ns3080769:~/pve-patches# bash pve-6.1-8-diff-backup-addon test
Proxmox VE 6.1-8 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

$ patch_apply / --dry-run --batch
checking file usr/share/pve-manager/js/pvemanagerlib.js
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #2 succeeded at 155 (offset 1 line).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5613 (offset 204 lines).
Hunk #2 FAILED at 5731.
Hunk #3 succeeded at 6458 (offset 405 lines).
1 out of 3 hunks FAILED
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 FAILED at 519.
Hunk #2 succeeded at 1404 with fuzz 1 (offset 125 lines).
Hunk #3 succeeded at 1450 (offset 125 lines).
1 out of 3 hunks FAILED
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Hunk #1 FAILED at 432.
Hunk #2 FAILED at 919.
2 out of 2 hunks FAILED
checking file usr/share/perl5/PVE/VZDump.pm
checking file usr/share/perl5/PVE/VZDump/Common.pm
Hunk #1 succeeded at 210 (offset 7 lines).
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 319 (offset 5 lines).
Hunk #2 succeeded at 414 (offset 5 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 243 with fuzz 2 (offset -6 lines).
Hunk #2 FAILED at 359.
1 out of 2 hunks FAILED

Best regards,
DECIGrade

**Comment by DECIGrade** [comment]
apt upgrade says me new version and install 6.1-11 manager version.
Acess web gui OK.

Script always fail (seems normal)

**Comment by dkmn-123** [comment]
Except script not working with 6.1.11 , I see that there is a new compression algorithm at the
original vzdump (zstd) .
Does it affect the operation of ayfan patches?

**Comment by DECIGrade** [comment]
Script always fail for 6.1-11

**Comment by DECIGrade** [comment]
New version of proxmox released, 6.2-4. Script always fail.

**Comment by ayufan** [comment]
Please use 6.2-4: https://github.com/ayufan/pve-patches/issues/50#issuecomment-633220165
