### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by swartjie** [ayufan/pve-patches#50]
Hey guys,

Ok so the updates were working well. Untill now I tried updating the addon, but when I run apply I get the below message, and I am not seeing the "Full Backup Every" option anymore...

root@c3:~/pve-patches# ./pve-6.1-8-diff-backup-addon apply
Proxmox VE 6.1-8 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 40632 (offset 2100 lines).
checking file usr/share/perl5/PVE/LXC/Create.pm
Hunk #2 succeeded at 155 (offset 1 line).
checking file usr/share/perl5/PVE/QemuServer.pm
Hunk #1 succeeded at 5613 (offset 204 lines).
Hunk #2 FAILED at 5731.
Hunk #3 succeeded at 6458 (offset 405 lines).
1 out of 3 hunks FAILED
checking file usr/share/perl5/PVE/Storage.pm
Hunk #1 FAILED at 519.
Hunk #2 succeeded at 1404 with fuzz 1 (offset 125 lines).
Hunk #3 succeeded at 1450 (offset 125 lines).
1 out of 3 hunks FAILED
checking file usr/share/perl5/PVE/Storage/Plugin.pm
Hunk #1 FAILED at 432.
Hunk #2 FAILED at 919.
2 out of 2 hunks FAILED
checking file usr/share/perl5/PVE/VZDump.pm
Hunk #2 succeeded at 638 (offset 9 lines).
Hunk #3 succeeded at 727 (offset 9 lines).
Hunk #4 succeeded at 949 (offset 9 lines).
Hunk #5 succeeded at 965 (offset 9 lines).
Hunk #6 succeeded at 983 with fuzz 2 (offset 9 lines).
checking file usr/share/perl5/PVE/VZDump/Common.pm
Hunk #1 succeeded at 210 (offset 7 lines).
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 319 (offset 5 lines).
Hunk #2 succeeded at 414 (offset 5 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
Hunk #1 succeeded at 243 with fuzz 2 (offset -6 lines).
Hunk #2 FAILED at 359.
1 out of 2 hunks FAILED
FAILED to apply!

**Comment by swartjie** [comment]
Please, any advise would be amazing!

**Comment by DaveB91** [comment]
I'm seeing the exact same thing
PVE 6.1-11

**Comment by DaveB91** [comment]
For the record - Now on 6.2-4
Still not working :(

**Comment by ayufan** [comment]
Will fix it next week :)

**Comment by ayufan** [comment]
Everyone. I don't know if I want to maintain it anymore. The amount of changes introduced recently makes it becoming extremely hard.

I think I might try to fix `6.2-4` but if the amount of changes gonna be high I might consider this archived.

**Comment by DaveB91** [comment]
Sad news

**Comment by ayufan** [comment]
OK. I tried to update it. It seems that in general works and I also rewrote a way how patch is generated, to make it also selfgenerating.

https://github.com/ayufan/pve-patches/blob/master/pve-6.2-4-diff-backup-addon

My unit tests do also seem to work across lxc/qemu and tar, gz, lzo and zstd. The patch requires updated xdelta3 with zstd support.

**Comment by DaveB91** [comment]
Perfect, thanks mate.
