### ISSUE TITLE
Error pve-6.2-4-diff-backup-addon

### ISSUE THREAD

**Issue by spions** [ayufan/pve-patches#53]
The patch did not work on the hypervisor installed yesterday:

root@prox1:~/pve-patches# bash pve-6.2-4-diff-backup-addon apply
Proxmox VE 6.2-4 - differential backup support, v3
Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

checking file usr/share/perl5/PVE/LXC/Create.pm
checking file usr/share/perl5/PVE/QemuServer.pm
checking file usr/share/perl5/PVE/Storage.pm
Hunk #2 succeeded at 1397 with fuzz 2.
Hunk #4 FAILED at 1453.
1 out of 4 hunks FAILED
checking file usr/share/perl5/PVE/Storage/Plugin.pm
checking file usr/share/perl5/PVE/VZDump.pm
checking file usr/share/perl5/PVE/VZDump/Common.pm
checking file usr/share/perl5/PVE/VZDump/LXC.pm
Hunk #1 succeeded at 319 (offset 2 lines).
Hunk #2 succeeded at 414 (offset 2 lines).
checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
checking file usr/share/pve-manager/js/pvemanagerlib.js
FAILED to apply!

**Comment by spions** [comment]
root@prox1:~/pve-patches# diff pve-6.2-4-diff-backup-addon pve-6.2-4-diff-backup-addon.bak
383c383
< -    PVE::Tools::run_command(['tar', '-xpOf', $archive, $file, '--occurrence'], outfunc => $out);
---
> -    run_command(['tar', '-xpOf', $archive, $file, '--occurrence'], outfunc => $out);

**Comment by ayufan** [comment]
https://github.com/ayufan/pve-patches/blob/master/pve-6.2-4-alt-diff-backup-addon
