### ISSUE TITLE
Installation error for Proxmox 6.2 on Debian Core

### ISSUE THREAD

**Issue by blower-jump** [ayufan/pve-patches#56]
I do not use the proxmox iso and install proxmox from repo on top of debian 10.
Follow your advices for installation. After install 

**`pve-xdelta3_3.0.11-dfsg-1ubuntu1.zstd.ayufan2_amd64.deb`** 

I repeat 

**`bash pve-6.1-8-diff-backup-addon apply`**

then came output:

root@intel-server:~/pve-patches# bash pve-6.1-8-diff-backup-addon apply
> Proxmox VE 6.1-8 - differential backup support, v3
> Kamil Trzcinski, http://ayufan.eu/, ayufan@ayufan.eu

> 
> checking file usr/share/pve-manager/js/pvemanagerlib.js
> Hunk #1 succeeded at 41663 (offset 3131 lines).
> checking file usr/share/perl5/PVE/LXC/Create.pm
> Hunk #2 succeeded at 155 (offset 1 line).
> checking file usr/share/perl5/PVE/QemuServer.pm
> Hunk #1 succeeded at 5621 (offset 212 lines).
> Hunk #2 FAILED at 5731.
> Hunk #3 succeeded at 6469 (offset 416 lines).
> 1 out of 3 hunks FAILED
> checking file usr/share/perl5/PVE/Storage.pm
> Hunk #1 FAILED at 519.
> Hunk #2 succeeded at 1404 with fuzz 1 (offset 125 lines).
> Hunk #3 FAILED at 1325.
> 2 out of 3 hunks FAILED
> checking file usr/share/perl5/PVE/Storage/Plugin.pm
> Hunk #1 FAILED at 432.
> Hunk #2 FAILED at 919.
> 2 out of 2 hunks FAILED
> checking file usr/share/perl5/PVE/VZDump.pm
> Hunk #2 succeeded at 640 (offset 11 lines).
> Hunk #3 FAILED at 718.
> Hunk #4 succeeded at 922 with fuzz 2 (offset 11 lines).
> Hunk #5 succeeded at 938 with fuzz 2 (offset 11 lines).
> Hunk #6 succeeded at 956 with fuzz 2 (offset 11 lines).
> 1 out of 6 hunks FAILED
> checking file usr/share/perl5/PVE/VZDump/Common.pm
> Hunk #1 succeeded at 210 (offset 7 lines).
> checking file usr/share/perl5/PVE/VZDump/LXC.pm
> Hunk #1 succeeded at 317 (offset 3 lines).
> Hunk #2 succeeded at 412 (offset 3 lines).
> checking file usr/share/perl5/PVE/VZDump/QemuServer.pm
> Hunk #1 succeeded at 243 with fuzz 2 (offset -6 lines).
> Hunk #2 FAILED at 359.
> 1 out of 2 hunks FAILED
> FAILED to apply!

Can you explain what happend?

**Comment by ayufan** [comment]
You should use patch for 6.2 not 6.1-8.
