### ISSUE TITLE
Would it be possible for Proxmox to make a full daily backup and every hour to make a differential backup?

### ISSUE THREAD

**Issue by viniciusbarretobr** [ayufan/pve-patches#6]
Hello, Congratulations on this work!
Would it be possible for Proxmox to make a full daily backup and every hour to make a differential backup of the VM?

Thanks in advance.
Best resgards

**Comment by sienar1** [comment]
Proxmox just uses CRON to schedule the backups. You could do that by hand yourself. Otherwise it would have to be done worked into the GUI and additional logic to write the backup tasks to the right CRON files.
