### ISSUE TITLE
Backup work, restore don't work.

### ISSUE THREAD

**Issue by KaleiRo** [ayufan/pve-patches#7]
Hi,

Nice to see you in github.

Backup is OK, but restore not :

TASK ERROR: file does not look like a template archive: /backups/dump/vzdump-lxc-104-2018_07_25-07_03_02.tar.gz--differential-2018_07_25-07_07_01.vcdiff

Proxmox-5.2 with ZFS file system.

**Comment by jskirke** [comment]
+1

**Comment by madnezzm** [comment]
+1


extracting from differential archive, using full backup '/var/lib/vz/dump/vzdump-qemu-100-2018_08_07-01_22_02.vma.lzo'
restore vma archive: pve-xdelta3 -q -d -c -R -s /var/lib/vz/dump/vzdump-qemu-100-2018_08_07-01_22_02.vma.lzo /var/lib/vz/dump/vzdump-qemu-100-2018_08_07-01_22_02.vma.lzo--differential-2018_08_07-01_31_02.vcdiff | vma extract -v -r /var/tmp/vzdumptmp27143.fifo - /var/tmp/vzdumptmp27143
TASK ERROR: command 'set -o pipefail && pve-xdelta3 -q -d -c -R -s /var/lib/vz/dump/vzdump-qemu-100-2018_08_07-01_22_02.vma.lzo /var/lib/vz/dump/vzdump-qemu-100-2018_08_07-01_22_02.vma.lzo--differential-2018_08_07-01_31_02.vcdiff | vma extract -v -r /var/tmp/vzdumptmp27143.fifo - /var/tmp/vzdumptmp27143' failed: got timeout

**Comment by khaledhu** [comment]
Same problem


extracting from differential archive, using full backup '/data/backup/dump/vzdump-qemu-100-2018_09_13-00_00_02.vma.gz'
restore vma archive: pve-xdelta3 -q -d -c -R -s /data/backup/dump/vzdump-qemu-100-2018_09_13-00_00_02.vma.gz /data/backup/dump/vzdump-qemu-100-2018_09_13-00_00_02.vma.gz--differential-2018_09_20-00_00_02.vcdiff | vma extract -v -r /var/tmp/vzdumptmp26844.fifo - /var/tmp/vzdumptmp26844
TASK ERROR: command 'set -o pipefail && pve-xdelta3 -q -d -c -R -s /data/backup/dump/vzdump-qemu-100-2018_09_13-00_00_02.vma.gz /data/backup/dump/vzdump-qemu-100-2018_09_13-00_00_02.vma.gz--differential-2018_09_20-00_00_02.vcdiff | vma extract -v -r /var/tmp/vzdumptmp26844.fifo - /var/tmp/vzdumptmp26844' failed: got timeout

Proxmox 5.2 with LVM over ISCSI

**Comment by ayufan** [comment]
This is resolved with latest patch for 5.3-9, it should work with 5.3-8 as well.
